#ifndef CONSTS_H
#define CONSTS_H

#define FPS 30
#define DISPLAY_WIDTH 1280
#define DISPLAY_HEIGHT 720
#define MAP_SIZE 2336
#define INITIAL_MAP_X -320
#define INITIAL_MAP_Y -90
#define PLAYER_WIDTH 100
#define PLAYER_HEIGHT 125
#define PLAYER_SPEED 6
#define BUTTON_WIDTH 178
#define BUTTON_HEIGHT 73
#define HEART_WIDTH 50
#define HEART_HEIGHT 45
#define HUNGER_WIDTH 50
#define FALLING_ACCELERATION 0.5
#define PLACEABLE_OBJECT_WIDTH 100
#define PLACEABLE_OBJECT_HEIGHT 100
#define SELECTABLE_OBJECT_WIDTH 100
#define SELECTABLE_OBJECT_HEIGHT 100
#define FALLING_OBJECT_WIDTH 50
#define FALLING_OBJECT_HEIGHT 50
#define WANTED_OBJECT_WIDTH 100
#define WANTED_OBJECT_HEIGHT 100
#define PLAY_BTN_X (DISPLAY_WIDTH / 2.0 - BUTTON_WIDTH / 2)
#define PLAY_BTN_Y 600
#define RETURN_TO_MENU_BTN_X PLAY_BTN_X
#define RETURN_TO_MENU_BTN_Y PLAY_BTN_Y

#endif
