#ifndef CONSTS_H
#define CONSTS_H

#define FPS 30
#define DISPLAY_WIDTH 1280
#define DISPLAY_HEIGHT 720
#define MAP_SIZE 2336
#define INITIAL_MAP_X -320
#define INITIAL_MAP_Y -90
#define PLAYER_WIDTH 100
#define PLAYER_HEIGHT 125
#define PLAYER_SPEED 6
#define BUTTON_WIDTH 100
#define BUTTON_HEIGHT 45
#define HEART_WIDTH 50
#define HEART_HEIGHT 45
#define HUNGER_WIDTH 50
#define HUNGER_HEIGHT 50
#define OXYGEN_WIDTH 50
#define OXYGEN_UNIT_DURATION 2
#define PLACEABLE_POSITION_WIDTH 100
#define PLACEABLE_POSITION_HEIGHT 100
#define FALLING_ACCELERATION 0.5
#define FALLING_OBJECT_WIDTH 50
#define FALLING_OBJECT_HEIGHT 50
#define PLAY_BTN_X (DISPLAY_WIDTH / 2.0 - BUTTON_WIDTH / 2)
#define PLAY_BTN_Y 600
#define TUTORIAL_BTN_X 1130
#define TUTORIAL_BTN_Y 630
#define CHALLENGE_NEXT_BTN_X TUTORIAL_BTN_X
#define CHALLENGE_NEXT_BTN_Y TUTORIAL_BTN_Y
#define RETURN_TO_MENU_BTN_X PLAY_BTN_X
#define RETURN_TO_MENU_BTN_Y PLAY_BTN_Y - 70
#define VOLUME_BTN_X 1200
#define VOLUME_BTN_Y 640

// types.h constants
#define SPRITES_LENGTH 3
#define PLACEABLE_OBJECTS_LENGTH 4
#define PLACEABLE_POSITIONS_LENGTH 8
#define SELECTABLE_OBJECTS_LENGTH_C2 7
#define SELECTABLE_OBJECTS_LENGTH_C5 8
#define FALLING_OBJECTS_LENGTH 16
#define WANTED_OBJECTS_LENGTH 5
#define OBSTACLES_LENGTH 71
#define SHALLOW_WATER_AREAS_LENGTH 6
#define ANIMALS_LENGTH 8 // 2 grupos de aves, 2 coelhos, 1 ovelha, bode, gato, cobra
#define TUTORIALS_LENGTH 16
#define RUB_SPRITES_LENGTH 4
#define ANIMAL_SOUNDS_LENGTH 4

#endif
